### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by ranjanport** [come-vishal/cricket.cpp#1]
I have seen you have copied my Github repository code with the changed name as I have found the code with Plagiarism. That matches to my code. `Building-Cricket-Game-Application-Updated-`

**Comment by Vishalport** [comment]
But how

**Comment by ranjanport** [comment]
Issue Closed As per request.

**Comment by ranjanport** [comment]
> I have seen you have copied my Github repository code with the changed name as I have found the code with Plagiarism. That matches to my code. `Building-Cricket-Game-Application-Updated-`

Issue Closed Copyright Removed Under EPL License. Type I'd : 935672292
